### ISSUE TITLE
string format

### ISSUE THREAD

**Issue by paulin-mipt** [EaglemanGo/crypy#3]
В местах вроде https://github.com/eaglemango/cipher-snake/blob/dev/ciphersnake.py#L17 не нужно складывать много строк. Гораздо эффективнее пользоваться методом `.format()`

Несмотря на то, что вы конструируете эти строчки по одному разу и сразу завершаете работу, писать так просто не принято, на всякий случай.

**Comment by eaglemango** [comment]
Форматирование строк приведено в порядок
