### ISSUE TITLE
del modules

### ISSUE THREAD

**Issue by paulin-mipt** [EaglemanGo/crypy#5]
https://github.com/eaglemango/cipher-snake/blob/24bed35d12bf1cb5e8fc1f2e9fd5495921fb2e77/cipherbook.py#L10
Но... зачем?

**Comment by eaglemango** [comment]
При использовании основого файла импортируется данный модуль. Однако ни одна из библиотек, использованных в `cipherbook.py` далее не используется в основном файле. В таком случае разве не следует удалить то, что не используется?

**Comment by paulin-mipt** [comment]
Нет, смысла в этом нет и так никто не делает. Ресурсов на это не тратится (по факту там тоже хранится всего одна ссылка)

**Comment by eaglemango** [comment]
Лишние строки убраны
