### ISSUE TITLE
import book

### ISSUE THREAD

**Issue by paulin-mipt** [EaglemanGo/crypy#6]
https://github.com/eaglemango/cipher-snake/blob/24bed35d12bf1cb5e8fc1f2e9fd5495921fb2e77/ciphersnake.py#L2

Интересный ход, но так всё-таки не делают. Не стоит полагаться на код, исполняемый при импорте модуля, если это не __init__.py, для того предназначенный.

Скучный способ -- обернуть конструирование book в функцию и вызывать её из cipherbook. Повеселее -- это сделать package (директорию) cipherbook, вынести туда же все шифры, и определить book внутри __init__.py. Тогда можно будет так же делать from `cipherbook import book`, но это будет правильнее (могу потом голосом рассказать, почему правильнее)

**Comment by eaglemango** [comment]
Генерация книги с шифрами перемещена в файл `__init__.py` соответствующего package.
