### ISSUE TITLE
argparse

### ISSUE THREAD

**Issue by paulin-mipt** [EaglemanGo/crypy#8]
Очень плоским получился главный файл. Обычно, если в блоке кода больше 20 строк, то есть шанс, что что-то идет не так. Давайте сделаем по функции на каждое действие? Можно даже смапить действия на них, типа 
```
actions = {
    'encrypt': encrypt_action,
...
}
```

А потом пользоваться как-то так:
```
try:
    actions[action](...)
except KeyError:
    print('Bad action: {}'.format(action))
```

**Comment by eaglemango** [comment]
Части кода вынесены в отдельные функции.
